// M6V.4 — the toolbar's icon names must all exist in the real registry.
//
// The chrome shipped with hand-authored `d` strings: approximations of Material Symbols
// that render as plausible-but-wrong glyphs, which no screenshot review reliably catches.
// The fix is to name icons and resolve them through the registry ported verbatim from the
// legacy adapter. This test pins the id → name mapping against the registry's actual
// exports, so the swap in `chrome-controls.ts` is mechanical and a typo fails here rather
// than rendering an empty box.

import { describe, expect, test } from 'bun:test';
import iconPaths from '../../vue/src/components/ui/icon-paths.json';
import { CHROME_GROUPS } from '@docx-editor.dev/core-contract/editor';

/**
 * control id → MATERIAL SYMBOL name.
 *
 * Not the React export name (`Bold`), which is what an earlier version of this table
 * used. `scripts/extract-icons.mjs` keys Vue's generated `icon-paths.json` by the
 * Material name (`format_bold`), so that is the only key both adapters can resolve: React
 * through its component registry, Vue through the JSON. Naming the descriptor after
 * React's exports would have made the generated file unusable from the shared descriptor.
 */
const ICON_FOR_CONTROL: Record<string, string> = {
  undo: 'undo',
  redo: 'redo',
  bold: 'format_bold',
  italic: 'format_italic',
  underline: 'format_underlined',
  strikethrough: 'strikethrough_s',
  superscript: 'superscript',
  subscript: 'subscript',
  fontColor: 'format_color_text',
  highlightColor: 'ink_highlighter',
  insertLink: 'link',
  clearFormatting: 'format_clear',
  alignLeft: 'format_align_left',
  alignCenter: 'format_align_center',
  alignRight: 'format_align_right',
  alignJustify: 'format_align_justify',
  lineSpacing: 'format_line_spacing',
  bulletList: 'format_list_bulleted',
  numberedList: 'format_list_numbered',
  decreaseIndent: 'format_indent_decrease',
  increaseIndent: 'format_indent_increase',
  insertImage: 'image',
  imageProperties: 'tune',
  insertTable: 'table',
  comments: 'comment',
  save: 'file_download',
};

describe('legacy icon mapping (M6V.4)', () => {
  test('every mapped name resolves in the GENERATED icon paths both adapters share', () => {
    // Generated by `scripts/extract-icons.mjs` from the React registry, so this asserts
    // the descriptor, the React components, and the Vue JSON all agree on one key set.
    const table = iconPaths as Record<string, readonly string[]>;
    const missing = Object.entries(ICON_FOR_CONTROL)
      .filter(([, name]) => !Array.isArray(table[name]) || table[name].length === 0)
      .map(([id, name]) => `${id} → ${name}`);
    expect(missing).toEqual([]);
  });

  test('every icon-bearing control has a mapping, so none is left hand-drawn', () => {
    const unmapped = CHROME_GROUPS.flatMap((g) => g.controls)
      .filter((c) => c.paths !== null && !ICON_FOR_CONTROL[c.id])
      .map((c) => c.id);
    expect(unmapped, 'controls still without a registry icon').toEqual([]);
  });

  test('the mapping names no control that does not exist', () => {
    const ids = new Set(CHROME_GROUPS.flatMap((g) => g.controls).map((c) => c.id));
    expect(Object.keys(ICON_FOR_CONTROL).filter((id) => !ids.has(id))).toEqual([]);
  });
});
