// Shared Paragraph dialog behavior is owned by core.
export {
  TWIPS_PER_INCH,
  twipsToInches,
  formatInches,
  inchesToTwips,
  type TabAlignment,
  type TabLeaderName,
  TAB_ALIGNMENT_LABELS,
  type SpecialIndent,
  specialOf,
  signedFirstLineOf,
  type ParagraphDialogFields,
  seedFields,
  type ParagraphDialogMixed,
  type ParagraphFlagKey,
  NO_MIXED_FIELDS,
  mixedFieldsOf,
  sameTabStops,
  changedFields,
  withTabStop,
  trapTabWithin,
} from '@docx-editor.dev/core/editor';
