// Canonical authored package model (document-engine task 2.9).
export {
  type RunProps,
  type RunRecord,
  type ParagraphProps,
  type ParagraphRecord,
  type BorderEdge,
  type Borders,
  type Shading,
  type TableWidth,
  type CellMargins,
  type TableProps,
  type TablePropsEx,
  type TableRowProps,
  type VMerge,
  type TableCellProps,
  type TableCellRecord,
  type TableRowRecord,
  type GridColumn,
  type TableRecord,
  type SdtLock,
  type SdtControlType,
  type SdtProps,
  type SdtRecord,
  type BlockRange,
  type PreservationState,
  type Block,
  type StoryKind,
  type Story,
  type StyleRecord,
  type DocDefaults,
  type NumberingRecord,
  type PartRecord,
  type IdentityState,
  type PackageModel,
  REL_TYPES,
  CONTENT_TYPES,
} from './authored-model.ts';
export { type IdKindName, IdentityAllocator } from './identity.ts';
export { createEmptyModel, bodyStoryId } from './create.ts';
export { type SerializedModel, encodeModel, decodeModel, validatePreservation } from './serialize.ts';
export { appendParagraph, insertParagraph, insertTextIntoParagraph, setParagraphRuns, paragraphText } from './edit.ts';
export { normalizeRuns } from './normalize-runs.ts';
export {
  type BlockKind,
  type CoreBlockCapability,
  type RecurseNormalize,
  type RecurseHash,
  registerCoreBlockCapability,
  blockHashContent,
  blockNormalize,
  blockSerialize,
  hasBlockSerialize,
} from './block-capabilities.ts';
export {
  type SplitResult,
  type ReplaceResult,
  type DeleteResult,
  splitRunsAt,
  splitParagraph,
  joinParagraphs,
  moveBlock,
  replaceParagraph,
  deleteParagraph,
  restoreParagraph,
} from './identity-ops.ts';
