// GENERATED by scripts/generate-manifest.mjs — do not edit.
// Regenerate with `bun run manifest` in packages/fonts; CI verifies via `manifest:check`.

/**
 * One packaged font asset, as measured at packaging time.
 *
 * `byteLength` and `hash` are baked here and CI-verified against the shipped files, so a
 * fetched asset is content-checked without hashing at runtime.
 */
export interface FontAssetManifestEntry {
  /** Asset filename under the package's `assets/` directory, e.g. `Carlito-Bold.ttf`. */
  readonly file: string;
  /** Exact packaged size. A fetch returning any other length is rejected. */
  readonly byteLength: number;
  /** `sha256:`-prefixed digest, re-derived and compared by the engine's admission path. */
  readonly hash: string;
}

/**
 * Every font asset this package ships, in generator order. Drives both
 * `loadDefaultFonts` (which looks entries up by filename) and the packaging check that
 * keeps the shipped bytes honest.
 */
export const FONT_ASSET_MANIFEST: readonly FontAssetManifestEntry[] = [
  {
    file: 'Caladea-Bold.ttf',
    byteLength: 84492,
    hash: 'sha256:ae3cb2dcbc925809dd29d2a44e9802211cab66be541bacbfc9c08c74b27c3742',
  },
  {
    file: 'Caladea-BoldItalic.ttf',
    byteLength: 83356,
    hash: 'sha256:ccabaa7b7e2fdf253d2b1a5fa699dd8a3df8d835a9eb285ad82631a677eb76c0',
  },
  {
    file: 'Caladea-Italic.ttf',
    byteLength: 83780,
    hash: 'sha256:4359a8e24f748b6447b1ff6d7a174febe70961d29f8bb8634b56dacd740a3deb',
  },
  {
    file: 'Caladea-Regular.ttf',
    byteLength: 81600,
    hash: 'sha256:f1e899278b7b4491aba5b6a8253c4b04c050cc59b21865be5c37559a775153cd',
  },
  {
    file: 'Carlito-Bold.ttf',
    byteLength: 682468,
    hash: 'sha256:bb5d20f79b82599ec72983597437373a80f2d2085fa91fc144fd74e876a594db',
  },
  {
    file: 'Carlito-BoldItalic.ttf',
    byteLength: 808508,
    hash: 'sha256:b32928186c119599e03ca6a1ffc680fdcb7fac95772f4b95d989cf6cd3861517',
  },
  {
    file: 'Carlito-Italic.ttf',
    byteLength: 615236,
    hash: 'sha256:0b019225e58d702bfedcbd35c21696769f8ee115cb6343f84c2f240312450d1c',
  },
  {
    file: 'Carlito-Regular.ttf',
    byteLength: 628032,
    hash: 'sha256:f6418f708baede9789daef5d458c0f53d2a888af9820e8062934e504fedc6595',
  },
  {
    file: 'LiberationMono-Bold.ttf',
    byteLength: 307996,
    hash: 'sha256:bd62a0672d0b9b6710b01df434c80ad54fa5f0835207eb7b17b7a761463067bb',
  },
  {
    file: 'LiberationMono-BoldItalic.ttf',
    byteLength: 284068,
    hash: 'sha256:79451f3c09fe25116098853b7a2ca6e2436220ccc11af022979adbcf195be130',
  },
  {
    file: 'LiberationMono-Italic.ttf',
    byteLength: 281536,
    hash: 'sha256:605c01c711b44480a7508d349dfbf3264e81fa43d69e61cfa7d10b86e764c4d1',
  },
  {
    file: 'LiberationMono-Regular.ttf',
    byteLength: 319508,
    hash: 'sha256:f2b83c763e8afd21709333370bed4774337fae82267937e2b5aea7e2fbd922c1',
  },
  {
    file: 'LiberationSans-Bold.ttf',
    byteLength: 414456,
    hash: 'sha256:788abee4c806d660e8aee46689dd8540cd4bb98da03dcc9d171ce3efd99a9173',
  },
  {
    file: 'LiberationSans-BoldItalic.ttf',
    byteLength: 408996,
    hash: 'sha256:698da70fc191cc5f33ad4d6d3fe830fe4624b898ea2e3169955928b7c491f1ee',
  },
  {
    file: 'LiberationSans-Italic.ttf',
    byteLength: 415816,
    hash: 'sha256:e5bae5c4cde31f22142753855f4f8fb86da6ff39955ed3c0a11248b0d16948b0',
  },
  {
    file: 'LiberationSans-Regular.ttf',
    byteLength: 410712,
    hash: 'sha256:76d04c18ea243f426b7de1f3ad208e927008f961dc5945e5aad352d0dfde8ee8',
  },
  {
    file: 'LiberationSerif-Bold.ttf',
    byteLength: 370096,
    hash: 'sha256:d754ba427cfe0bca54ae052384baa8f842da5bd6550ad4da024ac441e7a7d5ce',
  },
  {
    file: 'LiberationSerif-BoldItalic.ttf',
    byteLength: 376772,
    hash: 'sha256:f17db8af71e24d2066b587546021d4f0b296be389512b658dec3c09affeb11a7',
  },
  {
    file: 'LiberationSerif-Italic.ttf',
    byteLength: 375632,
    hash: 'sha256:0e3dea9f8d613e006ccfa62201f33e265d19167bd0907725c3e145368b04fc2e',
  },
  {
    file: 'LiberationSerif-Regular.ttf',
    byteLength: 393576,
    hash: 'sha256:058ea80864aef09a23f45cbec2bb5400bc3dfbdea01c3f10538a21fcb497fb74',
  },
  {
    file: 'TeXGyreAdventor-Bold.otf',
    byteLength: 180292,
    hash: 'sha256:881fcd422499d3c269697e37e4d483ee91a617a28428cdb6037029924dc47129',
  },
  {
    file: 'TeXGyreAdventor-BoldItalic.otf',
    byteLength: 179620,
    hash: 'sha256:a7aacff64987f83064eada3067887d7759675ac6286b7d1901fcc502b47f3822',
  },
  {
    file: 'TeXGyreAdventor-Italic.otf',
    byteLength: 174948,
    hash: 'sha256:f6e17fc59536385ffb1e8ed41a3c2b9d082f4a8bebd62d829283d0de50c0d3d4',
  },
  {
    file: 'TeXGyreAdventor-Regular.otf',
    byteLength: 174340,
    hash: 'sha256:17bfc0a97d48393453f28422f109d47099d54875600ea88a8d61c5ddd2dbffc4',
  },
];

/**
 * Bundler-visible URL for every packaged face. Each `new URL` argument is deliberately
 * a literal so Vite, webpack, and Turbopack emit the matching asset instead of collapsing
 * a dynamic template to one arbitrary file.
 *
 * @internal
 */
export const FONT_ASSET_URLS: Readonly<Record<string, URL>> = {
  'Caladea-Bold.ttf': new URL('../assets/Caladea-Bold.ttf', import.meta.url),
  'Caladea-BoldItalic.ttf': new URL('../assets/Caladea-BoldItalic.ttf', import.meta.url),
  'Caladea-Italic.ttf': new URL('../assets/Caladea-Italic.ttf', import.meta.url),
  'Caladea-Regular.ttf': new URL('../assets/Caladea-Regular.ttf', import.meta.url),
  'Carlito-Bold.ttf': new URL('../assets/Carlito-Bold.ttf', import.meta.url),
  'Carlito-BoldItalic.ttf': new URL('../assets/Carlito-BoldItalic.ttf', import.meta.url),
  'Carlito-Italic.ttf': new URL('../assets/Carlito-Italic.ttf', import.meta.url),
  'Carlito-Regular.ttf': new URL('../assets/Carlito-Regular.ttf', import.meta.url),
  'LiberationMono-Bold.ttf': new URL('../assets/LiberationMono-Bold.ttf', import.meta.url),
  'LiberationMono-BoldItalic.ttf': new URL(
    '../assets/LiberationMono-BoldItalic.ttf',
    import.meta.url
  ),
  'LiberationMono-Italic.ttf': new URL('../assets/LiberationMono-Italic.ttf', import.meta.url),
  'LiberationMono-Regular.ttf': new URL('../assets/LiberationMono-Regular.ttf', import.meta.url),
  'LiberationSans-Bold.ttf': new URL('../assets/LiberationSans-Bold.ttf', import.meta.url),
  'LiberationSans-BoldItalic.ttf': new URL(
    '../assets/LiberationSans-BoldItalic.ttf',
    import.meta.url
  ),
  'LiberationSans-Italic.ttf': new URL('../assets/LiberationSans-Italic.ttf', import.meta.url),
  'LiberationSans-Regular.ttf': new URL('../assets/LiberationSans-Regular.ttf', import.meta.url),
  'LiberationSerif-Bold.ttf': new URL('../assets/LiberationSerif-Bold.ttf', import.meta.url),
  'LiberationSerif-BoldItalic.ttf': new URL(
    '../assets/LiberationSerif-BoldItalic.ttf',
    import.meta.url
  ),
  'LiberationSerif-Italic.ttf': new URL('../assets/LiberationSerif-Italic.ttf', import.meta.url),
  'LiberationSerif-Regular.ttf': new URL('../assets/LiberationSerif-Regular.ttf', import.meta.url),
  'TeXGyreAdventor-Bold.otf': new URL('../assets/TeXGyreAdventor-Bold.otf', import.meta.url),
  'TeXGyreAdventor-BoldItalic.otf': new URL(
    '../assets/TeXGyreAdventor-BoldItalic.otf',
    import.meta.url
  ),
  'TeXGyreAdventor-Italic.otf': new URL('../assets/TeXGyreAdventor-Italic.otf', import.meta.url),
  'TeXGyreAdventor-Regular.otf': new URL('../assets/TeXGyreAdventor-Regular.otf', import.meta.url),
};
