/*
Copyright (c) 2026 EigenPal, Inc. All rights reserved.
Licensed under the EigenPal Pro Evaluation License 1.0 — see packages/editor-api/LICENSE.md.
Production use requires a commercial agreement: licensing@eigenpal.com
*/
/** Office field types. This runtime authors Page, NumPages, and Empty with a supported code. @public */
export enum FieldType {
  addin = 'Addin',
  addressBlock = 'AddressBlock',
  advance = 'Advance',
  ask = 'Ask',
  author = 'Author',
  autoText = 'AutoText',
  autoTextList = 'AutoTextList',
  barCode = 'BarCode',
  bibliography = 'Bibliography',
  bidiOutline = 'BidiOutline',
  citation = 'Citation',
  comments = 'Comments',
  compare = 'Compare',
  createDate = 'CreateDate',
  data = 'Data',
  database = 'Database',
  date = 'Date',
  displayBarcode = 'DisplayBarcode',
  docProperty = 'DocProperty',
  docVariable = 'DocVariable',
  editTime = 'EditTime',
  embedded = 'Embedded',
  empty = 'Empty',
  eq = 'EQ',
  expression = 'Expression',
  fileName = 'FileName',
  fileSize = 'FileSize',
  fillIn = 'FillIn',
  formCheckbox = 'FormCheckbox',
  formDropdown = 'FormDropdown',
  formText = 'FormText',
  gotoButton = 'GotoButton',
  greetingLine = 'GreetingLine',
  hyperlink = 'Hyperlink',
  if = 'If',
  import = 'Import',
  include = 'Include',
  includePicture = 'IncludePicture',
  includeText = 'IncludeText',
  index = 'Index',
  info = 'Info',
  keywords = 'Keywords',
  lastSavedBy = 'LastSavedBy',
  link = 'Link',
  listNum = 'ListNum',
  macroButton = 'MacroButton',
  mergeBarcode = 'MergeBarcode',
  mergeField = 'MergeField',
  mergeRec = 'MergeRec',
  mergeSeq = 'MergeSeq',
  next = 'Next',
  nextIf = 'NextIf',
  noteRef = 'NoteRef',
  numChars = 'NumChars',
  numPages = 'NumPages',
  numWords = 'NumWords',
  ocx = 'OCX',
  others = 'Others',
  page = 'Page',
  pageRef = 'PageRef',
  print = 'Print',
  printDate = 'PrintDate',
  private = 'Private',
  quote = 'Quote',
  rd = 'RD',
  ref = 'Ref',
  revNum = 'RevNum',
  saveDate = 'SaveDate',
  section = 'Section',
  sectionPages = 'SectionPages',
  seq = 'Seq',
  set = 'Set',
  shape = 'Shape',
  skipIf = 'SkipIf',
  styleRef = 'StyleRef',
  subject = 'Subject',
  subscriber = 'Subscriber',
  symbol = 'Symbol',
  ta = 'TA',
  tc = 'TC',
  template = 'Template',
  time = 'Time',
  title = 'Title',
  toa = 'TOA',
  toc = 'TOC',
  undefined = 'Undefined',
  userAddress = 'UserAddress',
  userInitials = 'UserInitials',
  userName = 'UserName',
  xe = 'XE',
}

/** String forms of Office field types. @public */
export type FieldTypeLiteral = `${FieldType}`;
