/** English UI text shared only by repository examples. */
type Variables = Record<string, string | number>;
const messages = {
  'collaborationDemo.title': 'Peer-to-peer collaboration proof',
  'collaborationDemo.subtitle': 'Run this page on two machines and open the same room link.',
  'collaborationDemo.name': 'Display name',
  'collaborationDemo.room': 'Room ID or link',
  'collaborationDemo.create': 'Create room',
  'collaborationDemo.join': 'Join room',
  'collaborationDemo.share': 'Share this join link',
  'collaborationDemo.copy': 'Copy link',
  'collaborationDemo.copied': 'Link copied',
  'collaborationDemo.connection': 'Room status',
  'collaborationDemo.peers': 'Connected participants',
  'collaborationDemo.disconnect': 'Disconnect',
  'collaborationDemo.reconnect': 'Reconnect',
  'collaborationDemo.undo': 'Undo',
  'collaborationDemo.redo': 'Redo',
  'collaborationDemo.save': 'Save DOCX',
  'collaborationDemo.scope':
    'This room replicates the whole document: text, formatting, tables, headers, and footers.',
  'collaborationDemo.warning':
    'Public signaling is for testing. Room links are not access control, storage, or a connectivity guarantee.',
  'collaborationDemo.failed': 'The collaboration proof could not start.',
  'collaborationDemo.connect': 'Connect',
  'collaborationDemo.online': 'online',
  'collaborationDemo.dialogTitle': 'Collaborate on this document',
  'collaborationDemo.dialogSubtitle': 'Share this document or join a room someone sent you.',
  'collaborationDemo.roomTitle': 'Collaboration room',
  'collaborationDemo.roomSubtitle': 'Everyone here sees document changes and live cursors.',
  'collaborationDemo.shareDocument': 'Share this document',
  'collaborationDemo.shareDescription': 'Create a room and copy an invite link.',
  'collaborationDemo.joinExisting': 'Join an existing room',
  'collaborationDemo.joinDescription': 'Open a room link from another collaborator.',
  'collaborationDemo.inviteLink': 'Invite link',
  'collaborationDemo.connected': 'Connected',
  'collaborationDemo.reconnecting': 'Reconnecting',
  'collaborationDemo.outOfSync': 'Out of sync. Reload to rejoin.',
  'collaborationDemo.outOfSyncShort': 'Out of sync',
  'collaborationDemo.person': 'person',
  'collaborationDemo.people': 'people',
  'collaborationDemo.you': 'You',
  'collaborationDemo.leave': 'Leave room',
  'collaborationDemo.done': 'Done',
  'collaborationDemo.close': 'Close collaboration dialog',
  'collaborationDemo.back': 'Back',
  'collaborationDemo.creating': 'Creating room…',
  'collaborationDemo.connecting': 'Connecting…',
  'collaborationDemo.enterRoom': 'Enter a room link or room ID.',
  'collaborationDemo.connectFailed': 'Could not connect to the room.',
  'collaborationDemo.leaveFailed': 'Could not leave the room.',
  'collaborationDemo.guest': 'Guest',
  'collaborationDemo.caretPages': ({ count }: Variables) =>
    `${count} ${Number(count) === 1 ? 'page' : 'pages'}`,
  'collaborationDemo.serverRecovery.upgradeGuide': 'Read the collaboration upgrade guide',
  'collaborationDemo.serverRecovery.versionTitle': 'This room needs a compatible app version.',
  'collaborationDemo.serverRecovery.versionBody':
    'Save a copy of any local changes first. Update the app and room server to compatible builds, then reload every open tab. For an older saved room, export its DOCX using the matching older build and open that file in a new room. Keep the saved room until its content has been recovered.',
  'collaborationDemo.serverRecovery.timeoutTitle': 'Room synchronization did not finish.',
  'collaborationDemo.serverRecovery.timeoutBody':
    'Check the server at {serverUrl}, your network connection, and the configured URL, then reload this page. If the demo server is not running, start it in a second terminal.',
  'collaborationDemo.serverRecovery.tokenBody':
    'Check COLLAB_TOKEN on the server against VITE_COLLAB_TOKEN here, then reconnect.',
  'collaborationDemo.serverRecovery.generalBody':
    'Save a copy of any local changes. Ask the room owner to resolve the connection problem before rejoining.',
  'collaborationDemo.serverRecovery.savedRoomTitle': 'The saved room could not be opened.',
  'collaborationDemo.serverRecovery.savedRoomBody':
    'Ask the room owner to check the saved files and server storage access. Keep the existing files; restore a working backup or recover a DOCX into a new room before trying again.',
  'documentRefresh.title': 'Server updates',
  'documentRefresh.description':
    'Receive two sample updates while you read. Your scroll position stays in place.',
  'documentRefresh.limitations':
    'Each update resets selection and undo history. Edits during processing prevent replacement.',
  'documentRefresh.start': 'Simulate server updates',
  'documentRefresh.cancel': 'Cancel updates',
  'documentRefresh.reset': 'Reset example',
  'documentRefresh.show': 'Highlight recent changes',
  'documentRefresh.clear': 'Clear highlights',
  'documentRefresh.previous': 'Previous change',
  'documentRefresh.next': 'Next change',
  'documentRefresh.retry': 'Restore document',
  'documentRefresh.download': 'Download recovery file',
  'documentRefresh.empty': 'No reliable change locations are available.',
  'documentRefresh.count': ({ count }: Variables) =>
    `${count} recent ${Number(count) === 1 ? 'change' : 'changes'}`,
  'documentRefresh.position': 'Change {current} of {total}',
  'documentRefresh.partial':
    '{count} processor operations failed. Successful changes remain applied.',
  'documentRefresh.idle': 'Ready for updates.',
  'documentRefresh.capturing': 'Preparing the document. Finish text composition to continue.',
  'documentRefresh.processing': 'Processing on the server. Edits made now prevent this update.',
  'documentRefresh.refreshing': 'Displaying the updated document.',
  'documentRefresh.recovering': 'Restoring your previous document.',
  'documentRefresh.complete': 'Document updated. Your scroll position stays in place.',
  'documentRefresh.failed': 'The update could not finish.',
  'documentRefresh.loadError': 'The example document could not load.',
  'documentRefresh.loading': 'Loading document…',
  'documentRefresh.localEdits':
    'Your edits are safe. Submit the document again to request an update.',
  'documentRefresh.invalidDocument': 'The returned file is invalid. Your document stays open.',
  'documentRefresh.recoveryFailed': 'Restore the document or download the recovery file.',
  'documentRefresh.cancelled': 'Updates cancelled.',
  'documentRefresh.unavailable': 'This change has no available location.',
  'documentRefresh.delivery': 'Delivery date',
  'documentRefresh.review': 'Review date',
  'documentRefresh.sampleDescription':
    'The mock replaces this sample. Reset the example before each test.',
  'documentRefresh.scrollToChange': 'Scroll to the change after the update',
  'documentRefresh.scrolled': 'Document updated. Scrolled to the changed paragraph.',
  'documentRefresh.processingLabel': 'Processing',
  'documentRefresh.sampleEdited':
    'Your edits stay in the document. Reset the sample to run this demo again.',
  'documentRefresh.lateResult': 'The late result was refused. The latest document stays open.',
  'documentRefresh.testLateResult': 'Deliver an older result after the latest update',
  'documentRefresh.reviewChanges': 'Review changes',
  'documentRefresh.showChange': 'Show change',
  'documentRefresh.changeStatus.available': 'Available location',
  'documentRefresh.changeStatus.deleted': 'Deleted content',
  'documentRefresh.changeStatus.unavailable': 'No highlight location',
  'documentRefresh.changeStatus.invalid': 'Invalid location',
  'documentRefresh.changeStatus.unsupported-story': 'Unsupported location',
  'anchorNavigation.title': 'Paragraph references',
  'anchorNavigation.description':
    'Choose a finding and an effect. The editor scrolls to the paragraph, highlights it, or both.',
  'anchorNavigation.reference': 'Reference',
  'anchorNavigation.effect': 'Effect',
  'anchorNavigation.style': 'Highlight style',
  'anchorNavigation.duration': 'Highlight duration',
  'anchorNavigation.position': 'Scroll position',
  'anchorNavigation.motion': 'Scroll motion',
  'anchorNavigation.show': 'Show reference',
  'anchorNavigation.clear': 'Clear highlight',
  'anchorNavigation.code': 'Calls for these settings',
  'anchorNavigation.ready': 'Choose a reference, and then select Show reference.',
  'anchorNavigation.cleared': 'The highlight is cleared.',
  'anchorNavigation.scrollFailed': 'This reference is unavailable. The document did not move.',
  'anchorNavigation.highlightFailed':
    'Scrolled to the reference. Highlights support body paragraphs and table cells only.',
  'anchorNavigation.highlightOnlyFailed':
    'This reference cannot receive a highlight. Highlights support body paragraphs and table cells only.',
  'anchorNavigation.references.payment': 'Payment terms',
  'anchorNavigation.references.fee': 'Annual support fee (table cell)',
  'anchorNavigation.references.liability': 'Second "Supplier" in the liability clause',
  'anchorNavigation.references.law': '"State of New York" in governing law',
  'anchorNavigation.references.header': 'Draft notice (header)',
  'anchorNavigation.references.missing': 'Deleted paragraph (missing)',
  'anchorNavigation.effects.both': 'Scroll and highlight',
  'anchorNavigation.effects.scroll': 'Scroll only',
  'anchorNavigation.effects.highlight': 'Highlight only',
  'anchorNavigation.styles.default': 'Default blue',
  'anchorNavigation.styles.amber': 'Amber with a dashed border',
  'anchorNavigation.styles.glow': 'Green glow (CSS class)',
  'anchorNavigation.styles.instant': 'Default blue without a fade',
  'anchorNavigation.durations.short': '1.5 seconds',
  'anchorNavigation.durations.default': '3 seconds',
  'anchorNavigation.durations.manual': 'Until cleared',
  'anchorNavigation.positions.centerIfNeeded': 'Center if needed',
  'anchorNavigation.positions.center': 'Center',
  'anchorNavigation.positions.start': 'Top of the viewport',
  'anchorNavigation.positions.nearest': 'Nearest edge',
  'anchorNavigation.motions.instant': 'Instant',
  'anchorNavigation.motions.smooth': 'Smooth',
  'anchorNavigation.done.both': 'Scrolled to the reference and highlighted it.',
  'anchorNavigation.done.scroll': 'Scrolled to the reference.',
  'anchorNavigation.done.highlight':
    'Highlighted the reference. If it is offscreen, scroll to see it.',
  'writerAgent.title': 'Writer agent',
  'writerAgent.subtitle': 'Edit documents with the document API',
  'writerAgent.empty': 'Describe a document or request an edit.',
  'writerAgent.placeholder': 'Describe the document or edit…',
  'writerAgent.send': 'Send',
  'writerAgent.working': 'Working…',
  'writerAgent.mode': 'Editing mode',
  'writerAgent.direct': 'Direct edits',
  'writerAgent.suggest': 'Suggestions',
  'writerAgent.notReady': 'The editor is not ready.',
  'writerAgent.suggestions.nda': 'Draft a mutual NDA.',
  'writerAgent.suggestions.intake': 'Create a medical intake form.',
  'writerAgent.suggestions.proposal': 'Write a project proposal.',
  'writerAgent.tools.read_document': 'Read document',
  'writerAgent.tools.inspect_document': 'Inspect document',
  'writerAgent.tools.discover_capabilities': 'Discover capabilities',
  'writerAgent.tools.create_document': 'Create document',
  'writerAgent.tools.format_lists': 'Format lists',
  'writerAgent.tools.insert_table': 'Insert table',
  'writerAgent.tools.insert_content_controls': 'Insert content controls',
  'writerAgent.tools.write_header_footer': 'Write header footer',
  'writerAgent.tools.propose_replacement': 'Propose replacement',
  'writerAgent.tools.propose_insertion': 'Propose insertion',
  'writerAgent.tools.propose_deletion': 'Propose deletion',
  'writerAgent.tools.format_document': 'Format document',
  'writerAgent.tools.edit_text': 'Edit text',
  'writerAgent.tools.edit_table': 'Edit table',
  'writerAgent.tools.edit_list': 'Edit list',
  'writerAgent.tools.configure_list': 'Configure list',
  'writerAgent.tools.edit_control': 'Edit control',
  'writerAgent.tools.edit_review': 'Edit review',
  'writerAgent.tools.edit_layout': 'Edit layout',
  'writerAgent.tools.insert_break': 'Insert break',
  'writerAgent.tools.edit_picture': 'Edit picture',
  'writerAgent.tools.edit_field': 'Edit field',
  'writerAgent.tools.write_story': 'Editing document text',
  'writerAgent.failed': 'Failed',
  'writerAgent.updatedParts': 'Updated {count} parts',
  'writerAgent.stop': 'Stop',
  'writerAgent.stopped': 'Generation stopped. Completed edits remain in the document.',
  'automationRecipes.badge': 'Document API',
  'automationRecipes.title': 'Document automation',
  'automationRecipes.subtitle': 'Run public document API examples.',
  'automationRecipes.show': 'Show document automation',
  'automationRecipes.hide': 'Hide document automation',
  'automationRecipes.inspect': 'Inspect paragraphs',
  'automationRecipes.search': 'Search text',
  'automationRecipes.insert': 'Insert text',
  'automationRecipes.format': 'Format text',
  'automationRecipes.select': 'Select a match',
  'automationRecipes.capabilities': 'Inspect host capabilities',
  'automationRecipes.expectedError': 'Try an unloaded property',
  'automationRecipes.expectedErrorMissing': 'The runtime did not report the expected error.',
  'automationRecipes.noParagraphs': 'The document has no paragraphs.',
  'automationRecipes.selectionUnavailable': 'This host cannot select text.',
  'automationRecipes.noMatch': 'No matching text is available.',
  'automationRecipes.query': 'Search text',
  'automationRecipes.result': 'Result',
  'automationRecipes.idle': 'Choose an example.',
  'automationRecipes.running': 'Running {recipe}.',
  'automationRecipes.expectedErrorStatus': '{recipe} reported the expected error.',
  'automationRecipes.succeeded': '{recipe} completed.',
  'automationRecipes.failed': '{recipe} failed.',
  'automationRecipes.license': 'Document automation requires the EigenPal Pro License.',
  'structuredAutomation.badge': 'Structured content',
  'structuredAutomation.title': 'Structured document automation',
  'structuredAutomation.subtitle': 'Inspect document objects and run supported edits.',
  'structuredAutomation.show': 'Show structured document automation',
  'structuredAutomation.hide': 'Hide structured document automation',
  'structuredAutomation.sections': 'Inspect sections and change a margin',
  'structuredAutomation.bookmarks': 'Inspect bookmarks',
  'structuredAutomation.notes': 'Inspect notes',
  'structuredAutomation.contentControls': 'Inspect and update a text control',
  'structuredAutomation.emptyCollection': 'The document has no sections.',
  'structuredAutomation.undoMargin': 'Use Undo to restore the previous margin.',
  'structuredAutomation.selectionUnsupported': 'This host cannot select or reveal bookmarks.',
  'structuredAutomation.bookmarkSelected': 'Selected bookmark {name}.',
  'structuredAutomation.bookmarkNotRun': 'The document has no bookmark to select.',
  'structuredAutomation.bookmarkScope': 'Bookmarks refer to ranges in the current document.',
  'structuredAutomation.noWritableControl': 'No eligible text control is available.',
  'structuredAutomation.undoControlValue': 'Use Undo to restore the control text.',
  'structuredAutomation.syncAuthority':
    'context.sync() reports document protection, control locks, and unsupported operations.',
  'structuredAutomation.result': 'Result',
  'structuredAutomation.idle': 'Choose an example.',
  'structuredAutomation.running': 'Running {recipe}.',
  'structuredAutomation.succeeded': '{recipe} completed.',
  'structuredAutomation.failed': '{recipe} failed.',
  'commentAutomation.badge': 'Comments API',
  'commentAutomation.title': 'Comment automation',
  'commentAutomation.subtitle': 'Inspect and edit existing comment threads.',
  'commentAutomation.show': 'Show comment automation',
  'commentAutomation.hide': 'Hide comment automation',
  'commentAutomation.inspect': 'Inspect comments',
  'commentAutomation.select': 'Select a comment range',
  'commentAutomation.selectionUnsupported': 'This host cannot select or reveal comment ranges.',
  'commentAutomation.noComments': 'The document has no comments.',
  'commentAutomation.noReplies': 'The selected comment has no replies.',
  'commentAutomation.reply': 'Add a reply',
  'commentAutomation.replyText': 'Reply text',
  'commentAutomation.undoReply': 'Use Undo to remove the reply.',
  'commentAutomation.resolve': 'Resolve or reopen a comment',
  'commentAutomation.undoResolved': 'Use Undo to restore the previous resolution state.',
  'commentAutomation.deleteReply': 'Delete a reply',
  'commentAutomation.undoDeleteReply': 'Use Undo to restore the deleted reply.',
  'commentAutomation.deleteComment': 'Delete a comment',
  'commentAutomation.undoDeleteComment': 'Use Undo to restore the deleted comment thread.',
  'commentAutomation.undo': 'Undo the last edit',
  'commentAutomation.boundaries': 'Example limits',
  'commentAutomation.creationAbsent':
    'This example edits existing comments. It does not create comments.',
  'commentAutomation.deleteSemantics': 'Deleting a comment also removes its replies.',
  'commentAutomation.replyCapability':
    'Reply operations require host comment support and an author.',
  'commentAutomation.fixture': 'Open a document with comments to run these examples.',
  'commentAutomation.result': 'Result',
  'commentAutomation.idle': 'Choose an example.',
  'commentAutomation.running': 'Running {recipe}.',
  'commentAutomation.succeeded': '{recipe} completed.',
  'commentAutomation.failed': '{recipe} failed.',
  'commentAutomation.license': 'Comment automation requires the EigenPal Pro License.',
  'consumerApi.title': 'Editor API',
  'consumerApi.subtitle': 'Inspect public editor state and run commands.',
  'consumerApi.show': 'Show editor API',
  'consumerApi.hide': 'Hide editor API',
  'consumerApi.eventChange': 'Document revision {revision}.',
  'consumerApi.eventSelection': 'Selection: page {current} of {total}.',
  'consumerApi.eventError': 'Editor error: {message}',
  'consumerApi.liveState': 'Live editor state',
  'consumerApi.page': 'Page',
  'consumerApi.zoom': 'Zoom',
  'consumerApi.mode': 'Editing mode',
  'consumerApi.selection': 'Selection',
  'consumerApi.caret': 'Caret',
  'consumerApi.range': 'Range',
  'consumerApi.on': 'on',
  'consumerApi.off': 'off',
  'consumerApi.yes': 'yes',
  'consumerApi.no': 'no',
  'consumerApi.formatting': 'Bold: {bold}. Italic: {italic}.',
  'consumerApi.noFormatting': 'No text formatting is available.',
  'consumerApi.toggleBold': 'Toggle bold',
  'consumerApi.useSuggesting': 'Use suggesting mode',
  'consumerApi.navigation': 'Navigation',
  'consumerApi.noSearchResults': 'No search results.',
  'consumerApi.next': 'Next match',
  'consumerApi.searchState': 'Search: {count} matches. Status: {pending}.',
  'consumerApi.pending': 'pending',
  'consumerApi.ready': 'ready',
  'consumerApi.noHeadings': 'No headings are available.',
  'consumerApi.firstHeading': 'Go to the first heading',
  'consumerApi.outlineState': 'Outline: {count} headings. Selected heading: {selected}.',
  'consumerApi.context': 'Selection context',
  'consumerApi.tableState':
    'Table: {rows} rows, {columns} columns. Cell: row {row}, column {column}.',
  'consumerApi.noTable': 'The selection is outside a table.',
  'consumerApi.imageState': 'Image {name}: {width} \u00d7 {height} pixels.',
  'consumerApi.noImage': 'No image is selected.',
  'consumerApi.imageWrap': 'Image wrapping',
  'consumerApi.notAvailable': 'Unavailable',
  'consumerApi.facade': 'Editor snapshot',
  'consumerApi.capture': 'Capture a snapshot',
  'consumerApi.captured': 'Page: {page}. Zoom: {zoom}. Mode: {mode}. Scope: {scope}.',
  'consumerApi.captureHint': 'Capture a snapshot to inspect plain editor state.',
  'consumerApi.events': 'Recent events',
  'consumerApi.noEvents': 'No events are available.',
  'reviewSettings.open': 'Review settings',
  'reviewSettings.title': 'Review display',
  'reviewSettings.subtitle': 'How comments and tracked changes appear. Saved in this browser.',
  'reviewSettings.close': 'Close review settings',
  'reviewSettings.reset': 'Reset to defaults',
  'reviewSettings.revisionsIn': 'Tracked changes',
  'reviewSettings.revisionsInHelp': 'Where a tracked change opens.',
  'reviewSettings.revisionsIn.pane': 'In the pane',
  'reviewSettings.revisionsIn.balloons': 'In balloons',
  'reviewSettings.commentMarkers': 'Comment markers',
  'reviewSettings.commentMarkersHelp':
    'How a comment looks in the margin while the pane is closed.',
  'reviewSettings.commentMarkers.initials': 'Initials',
  'reviewSettings.commentMarkers.icon': 'Icon',
  'reviewSettings.opening': 'Pane opening',
  'reviewSettings.openingHelp': 'Whether the pane opens when a document with comments loads.',
  'reviewSettings.opening.auto': 'Automatic',
  'reviewSettings.opening.manual': 'Manual',
  'reviewSettings.overflow': 'When the pane does not fit',
  'reviewSettings.overflow.float': 'Float',
  'reviewSettings.overflow.shrinkPage': 'Shrink page',
  'reviewSettings.overflow.scroll': 'Scroll',
  'reviewSettings.overflowHelp.float':
    'The pane becomes a strip of markers. The open card floats over the page.',
  'reviewSettings.overflowHelp.shrinkPage': 'The page shrinks so that the cards fit beside it.',
  'reviewSettings.overflowHelp.scroll':
    'The page keeps its size. Scroll sideways to see the cards.',
  'toolbar.exportPdfServerUnavailable':
    'PDF export is unavailable. Configure a Node.js server with @docx-editor.dev/docx-to-pdf.',
} as const;

export type ExampleTextKey = keyof typeof messages;

export function exampleText(key: ExampleTextKey, vars: Variables = {}): string {
  const message = messages[key];
  if (typeof message === 'function') return message(vars);
  if (message === undefined) return key;
  return message.replace(/\{(\w+)\}/g, (match, name: string) =>
    vars[name] === undefined ? match : String(vars[name])
  );
}
