import type { CanonicalStateFingerprint } from '../src/comparators/canonical-state';
import type { DecodedYjsModel } from '../src/comparators/yjs-schema-fingerprint';

export function canonicalState(): CanonicalStateFingerprint {
  return {
    revision: 1,
    paragraphs: [
      {
        blockId: 'block-para-003',
        paragraphId: 'para-003',
        text: 'hello',
        styleId: 'style-default',
        marks: [{ markId: 'mark-1', kind: 'bold', start: 0, end: 5 }],
        authoredProperties: {
          keepNext: { state: 'omitted' },
          lineHeight: { state: 'raw', rawLexical: '0240' },
        },
      },
    ],
    capsules: [
      {
        capsuleId: 'capsule-1',
        ownerBlockId: 'block-para-003',
        childIndex: 1,
        bytesHex: '00ff',
        namespaceBindings: { custom: 'urn:custom' },
        previousSiblingBytesHex: 'aa',
        nextSiblingBytesHex: 'bb',
      },
    ],
    anchors: [
      {
        anchorId: 'anchor-1',
        startEnvelope: 'start-relative',
        endEnvelope: 'end-relative',
        detached: false,
      },
    ],
    resultData: { changed: true },
  };
}

export function decodedYjsModel(): DecodedYjsModel {
  const provenance = (
    creationId: string,
    semanticId: string,
    proposedSemanticId: string,
    actorId: string,
    commitId: string
  ) => ({ creationId, semanticId, proposedSemanticId, actorId, commitId });
  const endpoint = {
    version: 'relative-endpoint/1' as const,
    documentId: 'doc-1',
    backendVersion: 'yjs-backend/1.0.0',
    schemaVersion: '1.0.0',
    checkpoint: 'checkpoint-1',
    textCreationId: 'actor-a:1:3',
    affinity: 'before' as const,
    relativeBytes: 'AQID',
  };
  return {
    documentId: 'doc-1',
    backendVersion: 'yjs-backend/1.0.0',
    schemaVersion: '1.0.0',
    normalizationVersion: '1.0.0',
    gcEnabled: false,
    rootContainerType: 'Y.Map',
    rootContainers: {
      meta: 'Y.Map',
      storyOrder: 'Y.Array',
      stories: 'Y.Map',
      blocks: 'Y.Map',
      texts: 'Y.Map',
      marks: 'Y.Map',
      capsules: 'Y.Map',
      allocator: 'Y.Map',
    },
    storyOrderContainerType: 'Y.Array',
    storyOrder: ['actor-a:1:1'],
    stories: [
      {
        ...provenance('actor-a:1:1', 'story-body', 'story-body', 'actor-a', 'commit-1'),
        containerType: 'Y.Map',
        storyKind: 'body',
        blockOrderContainerType: 'Y.Array',
        blockOrder: ['actor-a:1:2', 'actor-a:1:6', 'actor-b:1:1'],
      },
    ],
    blocks: [
      {
        ...provenance('actor-a:1:2', 'para-1', 'para-1', 'actor-a', 'commit-1'),
        containerType: 'Y.Map',
        storyId: 'actor-a:1:1',
        parentId: 'actor-a:1:1',
        blockKind: 'paragraph',
        paragraphId: 'para-1',
        proposedParagraphId: 'para-1',
        textId: 'actor-a:1:3',
        markIdsContainerType: 'Y.Array',
        markIds: ['actor-a:1:4'],
        capsuleIdsContainerType: 'Y.Array',
        capsuleIds: ['actor-a:1:5'],
        styleId: 'style-default',
        authoredProperties: {},
      },
      {
        ...provenance('actor-a:1:6', 'para-1-collision-actor-a-commit-1-6', 'para-1', 'actor-a', 'commit-1'),
        containerType: 'Y.Map',
        storyId: 'actor-a:1:1',
        parentId: 'actor-a:1:1',
        blockKind: 'paragraph',
        paragraphId: 'para-1-collision-actor-a-commit-1-6',
        proposedParagraphId: 'para-1',
        textId: 'actor-a:1:7',
        markIdsContainerType: 'Y.Array',
        markIds: [],
        capsuleIdsContainerType: 'Y.Array',
        capsuleIds: [],
        styleId: 'style-default',
        authoredProperties: {},
      },
      {
        ...provenance('actor-b:1:1', 'para-1-collision-actor-b-commit-1-1', 'para-1', 'actor-b', 'commit-1'),
        containerType: 'Y.Map',
        storyId: 'actor-a:1:1',
        parentId: 'actor-a:1:1',
        blockKind: 'paragraph',
        paragraphId: 'para-1-collision-actor-b-commit-1-1',
        proposedParagraphId: 'para-1',
        textId: 'actor-b:1:2',
        markIdsContainerType: 'Y.Array',
        markIds: [],
        capsuleIdsContainerType: 'Y.Array',
        capsuleIds: [],
        styleId: 'style-default',
        authoredProperties: {},
      },
    ],
    texts: [
      {
        ...provenance('actor-a:1:3', 'text-1', 'text-1', 'actor-a', 'commit-1'),
        parentBlockId: 'actor-a:1:2',
        containerType: 'Y.Map',
        contentContainerType: 'Y.Text',
        content: 'hello',
      },
      {
        ...provenance('actor-a:1:7', 'text-3', 'text-3', 'actor-a', 'commit-1'),
        parentBlockId: 'actor-a:1:6',
        containerType: 'Y.Map',
        contentContainerType: 'Y.Text',
        content: 'again',
      },
      {
        ...provenance('actor-b:1:2', 'text-2', 'text-2', 'actor-b', 'commit-1'),
        parentBlockId: 'actor-b:1:1',
        containerType: 'Y.Map',
        contentContainerType: 'Y.Text',
        content: 'world',
      },
    ],
    marks: [
      {
        ...provenance('actor-a:1:4', 'mark-1', 'mark-1', 'actor-a', 'commit-1'),
        containerType: 'Y.Map',
        parentTextId: 'actor-a:1:3',
        markKind: 'bold',
        start: endpoint,
        end: { ...endpoint, affinity: 'after', relativeBytes: 'BAUG' },
      },
    ],
    capsules: [
      {
        ...provenance('actor-a:1:5', 'capsule-1', 'capsule-1', 'actor-a', 'commit-1'),
        containerType: 'Y.Map',
        ownerStoryId: 'story-body',
        ownerBlockId: 'para-1',
        parentBlockId: 'actor-a:1:2',
        childIndex: 1,
        byteBoundaryStart: 0,
        byteBoundaryEnd: 2,
        bytesHex: '00ff',
        namespaceBindings: { custom: 'urn:custom' },
        previousSiblingBytesHex: 'aa',
        nextSiblingBytesHex: 'bb',
      },
    ],
    allocatorContainerType: 'Y.Map',
    allocator: [
      {
        containerType: 'Y.Map',
        actorId: 'actor-a',
        nextLocalSeq: 8,
        nextCommitSeq: 2,
        observedSemanticIdsContainerType: 'Y.Map',
        observedSemanticIds: [
          'capsule-1',
          'mark-1',
          'para-1',
          'para-1-collision-actor-a-commit-1-6',
          'story-body',
          'text-1',
          'text-3',
        ],
      },
      {
        containerType: 'Y.Map',
        actorId: 'actor-b',
        nextLocalSeq: 3,
        nextCommitSeq: 2,
        observedSemanticIdsContainerType: 'Y.Map',
        observedSemanticIds: ['para-1', 'para-1-collision-actor-b-commit-1-1', 'text-2'],
      },
      {
        containerType: 'Y.Map',
        actorId: 'actor-z',
        nextLocalSeq: 2,
        nextCommitSeq: 1,
        observedSemanticIdsContainerType: 'Y.Map',
        observedSemanticIds: ['deleted-1'],
      },
    ],
    collisionCandidates: [
      {
        creationId: 'actor-a:1:2',
        semanticId: 'para-1',
        proposedSemanticId: 'para-1',
        actorId: 'actor-a',
        commitId: 'commit-1',
      },
      {
        creationId: 'actor-a:1:6',
        semanticId: 'para-1-collision-actor-a-commit-1-6',
        proposedSemanticId: 'para-1',
        actorId: 'actor-a',
        commitId: 'commit-1',
      },
      {
        creationId: 'actor-b:1:1',
        semanticId: 'para-1-collision-actor-b-commit-1-1',
        proposedSemanticId: 'para-1',
        actorId: 'actor-b',
        commitId: 'commit-1',
      },
    ],
    splitTailEditJournal: [],
    tombstones: [
      {
        ...provenance('actor-z:0:1', 'deleted-1', 'deleted-1', 'actor-z', 'commit-0'),
        recordKind: 'mark',
        deleted: true,
      },
    ],
  };
}
