// WordprocessingML leaf serializers (document-engine task 2.10). Regenerate a single
// block's XML from the authored model. Attacker-derived text is XML-escaped. These are
// intentionally minimal (only the modeled run content); a caller that needs byte-faithful
// output uses verbatim preservation instead and only regenerates fully-captured blocks.

import { escapeXmlChecked } from './sinks.ts';
import { type Block, type ParagraphRecord, type ParagraphProps, type RunRecord, canonicalParagraphProps, registerCoreBlockCapability, blockSerialize } from '../model/index.ts';

/** Escape run text: validate fail-closed, then escape a literal CR as &#xD;. An unescaped CR is
 *  legal XML but silently normalized to LF by every parser's line-ending rule, so it would not
 *  survive a round-trip; the numeric reference preserves it exactly. */
function escapeRunText(text: string): string {
  return escapeXmlChecked(text, 'run text').replace(/\r/g, '&#xD;');
}

function runXml(run: RunRecord): string {
  // An ownership-scoped w:rPr capsule (verbatim, full run properties) is re-spliced INSTEAD of
  // regenerating rPr from the modeled bold/italic — the capsule already holds everything (incl. b/i).
  const props = run.props;
  const rPr = run.rPrCapsule
    ? run.rPrCapsule
    : props?.bold || props?.italic
      ? `<w:rPr>${props.bold ? '<w:b/>' : ''}${props.italic ? '<w:i/>' : ''}</w:rPr>`
      : '';
  return `<w:r>${rPr}<w:t xml:space="preserve">${escapeRunText(run.text)}</w:t></w:r>`;
}

/** Serialize modeled paragraph properties (w:pStyle / w:numPr) into a w:pPr. Used only when the
 *  paragraph carries no verbatim pPr capsule (a from-scratch or fully-modeled paragraph); a captured
 *  capsule always wins and is re-spliced verbatim instead. Props are canonicalized first so a
 *  degenerate value never emits (matching what the parser yields on reopen). */
function pPrFromProps(raw: ParagraphProps): string {
  const props = canonicalParagraphProps(raw);
  if (!props) return '';
  const pStyle = props.styleId ? `<w:pStyle w:val="${escapeXmlChecked(props.styleId, 'paragraph styleId')}"/>` : '';
  let numPr = '';
  if (props.numId !== undefined || props.ilvl !== undefined) {
    const ilvl = props.ilvl !== undefined ? `<w:ilvl w:val="${props.ilvl}"/>` : '';
    const numId = props.numId !== undefined ? `<w:numId w:val="${escapeXmlChecked(props.numId, 'numId')}"/>` : '';
    numPr = `<w:numPr>${ilvl}${numId}</w:numPr>`;
  }
  return pStyle || numPr ? `<w:pPr>${pStyle}${numPr}</w:pPr>` : '';
}

export function paragraphXml(p: ParagraphRecord): string {
  // Re-splice the ownership-scoped opening-tag ATTRIBUTES on <w:p …>. For the paragraph properties:
  // a verbatim pPr capsule wins (re-spliced byte-exact); otherwise emit modeled props (w:pStyle /
  // w:numPr) so a from-scratch or fully-modeled paragraph's style/numbering is not lost. Undefined
  // capsule + no props => `<w:p>` + runs only (byte-identical to the pre-capsule serializer).
  const pPr = p.pPrCapsule ?? (p.props ? pPrFromProps(p.props) : '');
  return `<w:p${p.pAttrsCapsule ?? ''}>${pPr}${p.runs.map(runXml).join('')}</w:p>`;
}

// Register the block-serialize capabilities (comprehensive 3.3). A paragraph regenerates from the
// coarse model; a TABLE or block-level SDT cannot be regenerated byte-faithfully (grid, borders,
// w14/w15 control payload would be lost), so its capability fails closed — the verbatim
// preservation range is the only byte-faithful source and is reused while unchanged.
registerCoreBlockCapability({ kind: 'paragraph', serialize: (block) => paragraphXml(block as ParagraphRecord) });
const failClosedSerialize = (what: string) => (): never => {
  throw new Error(`${what} regeneration is not implemented: byte-faithful output requires the verbatim preservation range`);
};
registerCoreBlockCapability({ kind: 'table', serialize: failClosedSerialize('table') });
registerCoreBlockCapability({ kind: 'sdt', serialize: failClosedSerialize('SDT') });

/** Regenerate one block's XML by dispatching to its registered serialize capability. */
export function blockXml(block: Block): string {
  return blockSerialize(block);
}
