// WordprocessingML leaf serializers (document-engine task 2.10). Regenerate a single
// block's XML from the authored model. Attacker-derived text is XML-escaped. These are
// intentionally minimal (only the modeled run content); a caller that needs byte-faithful
// output uses verbatim preservation instead and only regenerates fully-captured blocks.

import { escapeXml } from './sinks.ts';
import { type Block, type ParagraphRecord, type RunRecord, registerCoreBlockCapability, blockSerialize } from '../model/index.ts';
import { paragraphInnerWithCapsule } from './preservation-capsule.ts';

function runXml(run: RunRecord): string {
  // An ownership-scoped w:rPr capsule (verbatim, full run properties) is re-spliced INSTEAD of
  // regenerating rPr from the modeled bold/italic — the capsule already holds everything (incl. b/i).
  const props = run.props;
  const rPr = run.rPrCapsule
    ? run.rPrCapsule
    : props?.bold || props?.italic
      ? `<w:rPr>${props.bold ? '<w:b/>' : ''}${props.italic ? '<w:i/>' : ''}</w:rPr>`
      : '';
  return `<w:r>${rPr}<w:t xml:space="preserve">${escapeXml(run.text)}</w:t></w:r>`;
}

export function paragraphXml(p: ParagraphRecord): string {
  // Re-splice the ownership-scoped opening-tag ATTRIBUTES on <w:p …>, and the w:pPr capsule
  // (verbatim) ahead of the runs — the OOXML child order for w:p. Undefined capsules => `<w:p>` +
  // runs only (byte-identical to the pre-capsule serializer).
  return `<w:p${p.pAttrsCapsule ?? ''}>${paragraphInnerWithCapsule(p.pPrCapsule, p.runs.map(runXml).join(''))}</w:p>`;
}

// Register the block-serialize capabilities (comprehensive 3.3). A paragraph regenerates from the
// coarse model; a TABLE or block-level SDT cannot be regenerated byte-faithfully (grid, borders,
// w14/w15 control payload would be lost), so its capability fails closed — the verbatim
// preservation range is the only byte-faithful source and is reused while unchanged.
registerCoreBlockCapability({ kind: 'paragraph', serialize: (block) => paragraphXml(block as ParagraphRecord) });
const failClosedSerialize = (what: string) => (): never => {
  throw new Error(`${what} regeneration is not implemented: byte-faithful output requires the verbatim preservation range`);
};
registerCoreBlockCapability({ kind: 'table', serialize: failClosedSerialize('table') });
registerCoreBlockCapability({ kind: 'sdt', serialize: failClosedSerialize('SDT') });

/** Regenerate one block's XML by dispatching to its registered serialize capability. */
export function blockXml(block: Block): string {
  return blockSerialize(block);
}
