#!/usr/bin/env python3
"""Render two PDFs and create deterministic pixel-difference artifacts."""

from __future__ import annotations

import argparse
import json
import math
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

from PIL import __version__ as pillow_version
from PIL import Image, ImageChops, ImageDraw, ImageOps, ImageStat

DEFAULT_THRESHOLDS = (0, 8, 16, 28, 64)
MARKER = ".pdf-visual-diff"


def command_path(name: str) -> str:
    path = shutil.which(name)
    if path is None:
        raise RuntimeError(f"Required command is not installed: {name}")
    return path


def run(command: list[str], timeout_seconds: int = 120) -> str:
    return subprocess.check_output(
        command,
        stderr=subprocess.STDOUT,
        text=True,
        timeout=timeout_seconds,
    )


def document_info(pdf: Path, max_pages: int, timeout_seconds: int) -> dict[str, Any]:
    tool = command_path("pdfinfo")
    summary = run([tool, str(pdf)], timeout_seconds)
    page_match = re.search(r"^Pages:\s+(\d+)", summary, re.MULTILINE)
    if page_match is None:
        raise RuntimeError(f"pdfinfo did not report a page count for {pdf}")
    pages = int(page_match.group(1))
    if pages > max_pages:
        raise RuntimeError(f"{pdf} has {pages} pages, above --max-pages {max_pages}")

    details = run([tool, "-f", "1", "-l", str(pages), str(pdf)], timeout_seconds)
    sizes: dict[int, tuple[float, float]] = {}
    for match in re.finditer(
        r"^Page\s+(\d+)\s+size:\s+([0-9.]+)\s+x\s+([0-9.]+)\s+pts",
        details,
        re.MULTILINE,
    ):
        sizes[int(match.group(1))] = (float(match.group(2)), float(match.group(3)))
    if len(sizes) != pages:
        raise RuntimeError(f"pdfinfo did not report every page size for {pdf}")
    return {"pages": pages, "sizesPt": [sizes[page] for page in range(1, pages + 1)]}


def render_size(size_pt: tuple[float, float], dpi: int) -> tuple[int, int]:
    return (
        math.ceil(size_pt[0] * dpi / 72),
        math.ceil(size_pt[1] * dpi / 72),
    )


def validate_render_budget(
    reference: dict[str, Any],
    candidate: dict[str, Any],
    dpi: int,
    max_pixels: int,
    max_total_pixels: int,
) -> int:
    pages = max(reference["pages"], candidate["pages"])
    total = 0
    for index in range(pages):
        reference_size = (
            render_size(reference["sizesPt"][index], dpi)
            if index < reference["pages"]
            else (0, 0)
        )
        candidate_size = (
            render_size(candidate["sizesPt"][index], dpi)
            if index < candidate["pages"]
            else (0, 0)
        )
        width = max(reference_size[0], candidate_size[0])
        height = max(reference_size[1], candidate_size[1])
        pixels = width * height
        if pixels > max_pixels:
            raise RuntimeError(
                f"Page {index + 1} needs {pixels} pixels, above --max-pixels {max_pixels}"
            )
        total += pixels
        if total > max_total_pixels:
            raise RuntimeError(
                f"Comparison needs {total} pixels, above --max-total-pixels "
                f"{max_total_pixels}"
            )
    return total


def prepare_output(path: Path, force: bool) -> None:
    if path.exists() and any(path.iterdir()):
        if not force:
            raise RuntimeError(f"Output directory is not empty: {path}. Use --force to replace it.")
        if not (path / MARKER).is_file():
            raise RuntimeError(f"Refusing to replace an unmarked directory: {path}")
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)
    (path / MARKER).write_text("Generated by scripts/pdf-visual-diff.py\n", encoding="utf-8")


def rasterize_page(
    pdf: Path,
    output: Path,
    dpi: int,
    page: int,
    timeout_seconds: int,
) -> Path:
    output.mkdir(parents=True, exist_ok=True)
    tool = command_path("pdftoppm")
    target = output / f"page-{page:04d}"
    run(
        [
            tool,
            "-png",
            "-r",
            str(dpi),
            "-f",
            str(page),
            "-l",
            str(page),
            "-singlefile",
            str(pdf),
            str(target),
        ],
        timeout_seconds,
    )
    rendered = target.with_suffix(".png")
    if not rendered.is_file():
        raise RuntimeError(f"pdftoppm did not create {rendered}")
    return rendered


def pad(image: Image.Image, size: tuple[int, int]) -> Image.Image:
    rgb = image.convert("RGB")
    if rgb.size == size:
        return rgb
    canvas = Image.new("RGB", size, "white")
    canvas.paste(rgb, (0, 0))
    return canvas


def load_rgb(path: Path) -> Image.Image:
    with Image.open(path) as image:
        return image.convert("RGB")


def max_channel(image: Image.Image) -> Image.Image:
    red, green, blue = image.split()
    return ImageChops.lighter(ImageChops.lighter(red, green), blue)


def threshold_mask(magnitude: Image.Image, threshold: int) -> Image.Image:
    floor = max(1, threshold)
    return magnitude.point(lambda value: 255 if value >= floor else 0)


def contiguous_bands(values: list[int], merge_gap: int = 2) -> list[tuple[int, int]]:
    indices = [index for index, value in enumerate(values) if value]
    if not indices:
        return []
    bands: list[tuple[int, int]] = []
    start = previous = indices[0]
    for index in indices[1:]:
        if index - previous > merge_gap + 1:
            bands.append((start, previous + 1))
            start = index
        previous = index
    bands.append((start, previous + 1))
    return bands


def save_artifacts(
    reference: Image.Image,
    candidate: Image.Image,
    difference: Image.Image,
    all_mask: Image.Image,
    strong_mask: Image.Image,
    output: Path,
    label: str,
) -> None:
    reference.save(output / "reference.png", compress_level=9)
    candidate.save(output / "candidate.png", compress_level=9)

    amplified = difference.point(lambda value: min(255, value * 8))
    amplified.save(output / "diff-amplified.png", compress_level=9)

    gray = ImageOps.grayscale(candidate).convert("RGB")
    red = Image.new("RGB", candidate.size, (255, 32, 32))
    all_alpha = all_mask.point(lambda value: 160 if value else 0)
    overlay = Image.composite(red, gray, all_alpha)
    overlay.save(output / "diff-overlay.png", compress_level=9)
    strong_alpha = strong_mask.point(lambda value: 180 if value else 0)
    strong_overlay = Image.composite(red, gray, strong_alpha)
    strong_overlay.save(output / "diff-overlay-strong.png", compress_level=9)

    gap = 12
    header = 32
    width, height = candidate.size
    montage = Image.new("RGB", (width * 3 + gap * 2, height + header), (32, 32, 32))
    draw = ImageDraw.Draw(montage)
    draw.text((8, 8), "reference", fill="white")
    draw.text((width + gap + 8, 8), "candidate", fill="white")
    draw.text((width * 2 + gap * 2 + 8, 8), label, fill="white")
    montage.paste(reference, (0, header))
    montage.paste(candidate, (width + gap, header))
    montage.paste(amplified, (width * 2 + gap * 2, header))
    montage.save(output / "montage.png", compress_level=9)


def compare_page(
    reference_path: Path | None,
    candidate_path: Path | None,
    output: Path,
    dpi: int,
    thresholds: tuple[int, ...],
    strong_threshold: int,
    max_pixels: int,
) -> dict[str, Any]:
    reference_source = load_rgb(reference_path) if reference_path else None
    candidate_source = load_rgb(candidate_path) if candidate_path else None
    available = reference_source or candidate_source
    if available is None:
        raise RuntimeError("A page needs at least one rendered image")
    size = (
        max(reference_source.width if reference_source else 0, candidate_source.width if candidate_source else 0),
        max(reference_source.height if reference_source else 0, candidate_source.height if candidate_source else 0),
    )
    pixels = size[0] * size[1]
    if pixels > max_pixels:
        raise RuntimeError(f"Rendered page has {pixels} pixels, above --max-pixels {max_pixels}")

    blank = Image.new("RGB", size, "white")
    reference = pad(reference_source, size) if reference_source else blank.copy()
    candidate = pad(candidate_source, size) if candidate_source else blank.copy()
    difference = ImageChops.difference(reference, candidate)
    magnitude = max_channel(difference)
    histogram = magnitude.histogram()
    counts = {
        str(threshold): sum(histogram[max(1, threshold) :])
        for threshold in thresholds
    }
    all_mask = threshold_mask(magnitude, 0)
    strong_mask = threshold_mask(magnitude, strong_threshold)
    bbox = strong_mask.getbbox()
    x_projection, y_projection = strong_mask.getprojection()
    bands = contiguous_bands(y_projection)
    stat = ImageStat.Stat(difference)
    mean_absolute = sum(stat.mean) / 3
    root_mean_square = math.sqrt(sum(value * value for value in stat.rms) / 3)

    output.mkdir(parents=True, exist_ok=True)
    strong_count = counts[str(strong_threshold)]
    label = f"diff x8 | >= {strong_threshold}: {strong_count / pixels:.3%}"
    save_artifacts(
        reference,
        candidate,
        difference,
        all_mask,
        strong_mask,
        output,
        label,
    )

    points_per_pixel = 72 / dpi
    return {
        "referencePresent": reference_path is not None,
        "candidatePresent": candidate_path is not None,
        "referenceSizePx": list(reference_source.size) if reference_source else None,
        "candidateSizePx": list(candidate_source.size) if candidate_source else None,
        "canvasSizePx": list(size),
        "sizeMismatch": reference_source is not None
        and candidate_source is not None
        and reference_source.size != candidate_source.size,
        "pixelCount": pixels,
        "changedPixelsByThreshold": counts,
        "changedFractionByThreshold": {
            key: round(value / pixels, 8) for key, value in counts.items()
        },
        "meanAbsoluteDifference": round(mean_absolute, 5),
        "rootMeanSquareDifference": round(root_mean_square, 5),
        "strongDifferenceBoundsPx": list(bbox) if bbox else None,
        "strongDifferenceBoundsPt": (
            [round(value * points_per_pixel, 3) for value in bbox] if bbox else None
        ),
        "strongDifferenceBandsPx": [list(band) for band in bands],
        "strongDifferenceBandsPt": [
            [round(value * points_per_pixel, 3) for value in band] for band in bands
        ],
        "artifacts": {
            "reference": str(output / "reference.png"),
            "candidate": str(output / "candidate.png"),
            "amplified": str(output / "diff-amplified.png"),
            "overlay": str(output / "diff-overlay.png"),
            "strongOverlay": str(output / "diff-overlay-strong.png"),
            "montage": str(output / "montage.png"),
        },
    }


def parse_thresholds(raw: str, strong: int) -> tuple[int, ...]:
    if not 0 <= strong <= 255:
        raise ValueError("--strong-threshold must be between 0 and 255")
    values = {strong}
    for part in raw.split(","):
        value = int(part.strip())
        if not 0 <= value <= 255:
            raise ValueError("Thresholds must be between 0 and 255")
        values.add(value)
    return tuple(sorted(values))


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(
        description="Render two PDFs to lossless PNGs and highlight pixel differences."
    )
    result.add_argument("reference", type=Path)
    result.add_argument("candidate", type=Path)
    result.add_argument("--output", required=True, type=Path)
    result.add_argument("--dpi", type=int, default=150)
    result.add_argument("--thresholds", default="0,8,16,28,64")
    result.add_argument("--strong-threshold", type=int, default=28)
    result.add_argument("--max-pages", type=int, default=500)
    result.add_argument("--max-pixels", type=int, default=40_000_000)
    result.add_argument("--max-total-pixels", type=int, default=250_000_000)
    result.add_argument("--timeout-seconds", type=int, default=120)
    result.add_argument("--force", action="store_true")
    result.add_argument("--fail-above-percent", type=float)
    return result


def main(arguments: list[str] | None = None) -> int:
    options = parser().parse_args(arguments)
    if not 36 <= options.dpi <= 600:
        raise ValueError("--dpi must be between 36 and 600")
    if not 1 <= options.max_pages <= 10_000:
        raise ValueError("--max-pages must be between 1 and 10000")
    if options.max_pixels < 1 or options.max_total_pixels < 1:
        raise ValueError("Pixel limits must be positive")
    if not 1 <= options.timeout_seconds <= 3_600:
        raise ValueError("--timeout-seconds must be between 1 and 3600")
    if options.fail_above_percent is not None and options.fail_above_percent < 0:
        raise ValueError("--fail-above-percent must not be negative")
    for pdf in (options.reference, options.candidate):
        if not pdf.is_file():
            raise FileNotFoundError(pdf)
    thresholds = parse_thresholds(options.thresholds, options.strong_threshold)
    reference_info = document_info(
        options.reference,
        options.max_pages,
        options.timeout_seconds,
    )
    candidate_info = document_info(
        options.candidate,
        options.max_pages,
        options.timeout_seconds,
    )
    reference_pages = reference_info["pages"]
    candidate_pages = candidate_info["pages"]
    compared_pages = max(reference_pages, candidate_pages)
    estimated_pixels = validate_render_budget(
        reference_info,
        candidate_info,
        options.dpi,
        options.max_pixels,
        options.max_total_pixels,
    )
    prepare_output(options.output, options.force)

    page_reports: list[dict[str, Any]] = []
    with tempfile.TemporaryDirectory(prefix="pdf-visual-diff-") as temporary:
        temporary_root = Path(temporary)
        for index in range(compared_pages):
            reference_rendered = (
                rasterize_page(
                    options.reference,
                    temporary_root / "reference",
                    options.dpi,
                    index + 1,
                    options.timeout_seconds,
                )
                if index < reference_pages
                else None
            )
            candidate_rendered = (
                rasterize_page(
                    options.candidate,
                    temporary_root / "candidate",
                    options.dpi,
                    index + 1,
                    options.timeout_seconds,
                )
                if index < candidate_pages
                else None
            )
            page_reports.append(
                compare_page(
                    reference_rendered,
                    candidate_rendered,
                    options.output / "pages" / f"page-{index + 1:04d}",
                    options.dpi,
                    thresholds,
                    options.strong_threshold,
                    options.max_pixels,
                )
            )
            if reference_rendered:
                reference_rendered.unlink()
            if candidate_rendered:
                candidate_rendered.unlink()

    total_pixels = sum(page["pixelCount"] for page in page_reports)
    if total_pixels > options.max_total_pixels:
        raise RuntimeError(
            f"Rendered comparison has {total_pixels} pixels, above --max-total-pixels "
            f"{options.max_total_pixels}"
        )
    aggregate_counts = {
        str(threshold): sum(
            page["changedPixelsByThreshold"][str(threshold)] for page in page_reports
        )
        for threshold in thresholds
    }
    report = {
        "schemaVersion": 1,
        "reference": str(options.reference.resolve()),
        "candidate": str(options.candidate.resolve()),
        "dpi": options.dpi,
        "tools": {
            "pillow": pillow_version,
            "pdfinfo": run(
                [command_path("pdfinfo"), "-v"],
                options.timeout_seconds,
            ).splitlines()[0],
            "pdftoppm": run(
                [command_path("pdftoppm"), "-v"],
                options.timeout_seconds,
            ).splitlines()[0],
        },
        "thresholds": list(thresholds),
        "strongThreshold": options.strong_threshold,
        "limits": {
            "maxPages": options.max_pages,
            "maxPixels": options.max_pixels,
            "maxTotalPixels": options.max_total_pixels,
            "timeoutSeconds": options.timeout_seconds,
        },
        "referencePages": reference_pages,
        "candidatePages": candidate_pages,
        "pageCountMismatch": reference_pages != candidate_pages,
        "estimatedPixels": estimated_pixels,
        "totalPixels": total_pixels,
        "changedPixelsByThreshold": aggregate_counts,
        "changedFractionByThreshold": {
            key: round(value / total_pixels, 8) for key, value in aggregate_counts.items()
        },
        "pages": page_reports,
    }
    report_path = options.output / "report.json"
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    strong_fraction = report["changedFractionByThreshold"][str(options.strong_threshold)]
    print(
        json.dumps(
            {
                "report": str(report_path),
                "pages": compared_pages,
                "pageCountMismatch": report["pageCountMismatch"],
                "strongChangedPercent": round(strong_fraction * 100, 4),
            },
            indent=2,
        )
    )
    if (
        options.fail_above_percent is not None
        and strong_fraction * 100 > options.fail_above_percent
    ):
        return 2
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (
        OSError,
        RuntimeError,
        ValueError,
        subprocess.CalledProcessError,
        subprocess.TimeoutExpired,
    ) as error:
        print(f"pdf-visual-diff: {error}", file=sys.stderr)
        raise SystemExit(1)
