/** Application tool coverage of the repository's pinned editing profile. */
export const EDITING_COVERAGE: Record<string, readonly string[]> = {
  inspect_document_batch: ['Body.paragraphs', 'Body.tables', 'Body.footnotes', 'Body.endnotes'],
  read_properties: ['Document.properties', 'DocumentProperties.lastAuthor'],
  remove_document_properties: ['Document.removeDocumentInformation'],
  edit_properties: [
    'DocumentProperties.author',
    'DocumentProperties.title',
    'DocumentProperties.subject',
    'DocumentProperties.keywords',
    'DocumentProperties.comments',
    'DocumentProperties.category',
  ],
  create_document: ['Body.insertParagraph', 'Paragraph.insertText', 'Paragraph.style'],
  edit_text: ['Range.insertText', 'Range.delete', 'Paragraph.delete', 'Range.insertParagraph'],
  format_document: [
    'Range.hyperlink',
    'Font.bold',
    'Font.italic',
    'Font.underline',
    'Font.strikeThrough',
    'Font.name',
    'Font.size',
    'Font.color',
    'Font.highlightColor',
    'Font.subscript',
    'Font.superscript',
    'Paragraph.alignment',
    'Paragraph.leftIndent',
    'Paragraph.rightIndent',
    'Paragraph.firstLineIndent',
    'Paragraph.lineSpacing',
    'Paragraph.spaceBefore',
    'Paragraph.spaceAfter',
    'Paragraph.readingOrder',
  ],
  edit_review: [
    'Range.insertComment',
    'Comment.reply',
    'Comment.resolved',
    'Comment.delete',
    'CommentReply.delete',
    'Revision.accept',
    'Revision.reject',
    'RevisionCollection.acceptAll',
    'RevisionCollection.rejectAll',
  ],
  edit_list: [
    'Paragraph.startNewList',
    'Paragraph.attachToList',
    'Paragraph.detachFromList',
    'ListItem.level',
  ],
  configure_list: [
    'List.setLevelBullet',
    'List.setLevelNumbering',
    'List.setLevelStartingNumber',
    'List.setLevelIndents',
  ],
  insert_table: ['Range.insertTable'],
  edit_table: [
    'Table.values',
    'Table.addRows',
    'TableRow.insertRows',
    'Table.deleteRows',
    'Table.addColumns',
    'Table.deleteColumns',
    'Table.delete',
    'Table.headerRowCount',
    'Table.style',
    'TableCell.value',
    'TableCell.columnWidth',
    'TableCell.shadingColor',
    'TableCell.verticalAlignment',
  ],
  insert_break: ['Range.insertBreak'],
  edit_layout: [
    'PageSetup.orientation',
    'PageSetup.pageWidth',
    'PageSetup.pageHeight',
    'PageSetup.leftMargin',
    'PageSetup.rightMargin',
    'PageSetup.topMargin',
    'PageSetup.bottomMargin',
  ],
  insert_content_controls: ['Range.insertContentControl'],
  edit_control: [
    'ContentControl.tag',
    'ContentControl.title',
    'ContentControl.insertText',
    'ContentControl.delete',
    'ContentControl.cannotEdit',
    'ContentControl.cannotDelete',
  ],
  edit_picture: [
    'Range.insertInlinePictureFromBase64',
    'InlinePicture.delete',
    'InlinePicture.width',
    'InlinePicture.height',
    'InlinePicture.lockAspectRatio',
    'InlinePicture.altTextDescription',
  ],
  edit_field: ['Range.insertField', 'Field.code', 'Field.updateResult', 'Field.delete'],
  write_header_footer: ['Body.insertText'],
};
export const APPLICATION_COVERAGE = ['Document.changeTrackingMode'] as const;
