// Compile-time policy boundary between the evolving semantic IR and Markdown representation.

import type {
  AnchoredDrawingRecord,
  EquationSpanRecord,
  HeaderFooterStoryRecord,
  InlineDrawingRecord,
  LineRecord,
  ListMarkerRecord,
  NoteAreaRecord,
  NoteStoryRecord,
  PageRecord,
  ParagraphFragmentRecord,
  SemanticLayout,
  SourceRange,
  SpanLinkRecord,
  StyleSpanRecord,
  TableCellFragmentRecord,
  TableFragmentRecord,
  TableRowFragmentRecord,
  RevisionAttribution,
  RevisionDisplayMode,
  RevisionKind,
  ResolvedRunStyle,
  SemanticRootStoryKind,
  TextboxStoryLayout,
} from '@docx-editor.dev/core/layout';
import type { ImageResourceState } from '@docx-editor.dev/core/store';

type DrawingAccessibility = InlineDrawingRecord['accessibility'];

type MarkdownFieldPolicy =
  | 'represented'
  | 'callback-exposed'
  | 'layout-only'
  | 'explicitly-omitted';

/**
 * `represented` means the translator reads the field to determine emitted Markdown, ordering, or
 * grouping. `callback-exposed` means the image callback receives it but core emits no syntax for
 * it. `layout-only` means its effect is already baked into layout/projection and the translator
 * does not read it. `explicitly-omitted` is an intentional semantic degradation.
 *
 * These maps deliberately enumerate every field consumed at the exporter boundary. A new core
 * semantic field must receive an explicit Markdown policy before TypeScript will pass. Behavioral
 * tests remain the authority for what each represented field emits.
 */
const MARKDOWN_SEMANTIC_POLICY_RATCHETS = Object.freeze({
  span: {
    range: 'represented',
    text: 'represented',
    props: 'explicitly-omitted',
    style: 'represented',
    box: 'layout-only',
    caretEdges: 'layout-only',
    tabLeader: 'explicitly-omitted',
    tabLeaderAdvancePt: 'layout-only',
    link: 'represented',
    wrapAdvanceBefore: 'layout-only',
    revisions: 'represented',
    fieldAtom: 'explicitly-omitted',
    projected: 'layout-only',
    equation: 'represented',
    noteNav: 'represented',
  } satisfies Record<keyof StyleSpanRecord, MarkdownFieldPolicy>,
  sourceRange: {
    paragraphId: 'represented',
    start: 'represented',
    end: 'represented',
  } satisfies Record<keyof SourceRange, MarkdownFieldPolicy>,
  runStyle: {
    fontFamily: 'layout-only',
    fontSizePt: 'layout-only',
    color: 'explicitly-omitted',
    bold: 'represented',
    italic: 'represented',
    underline: 'explicitly-omitted',
    strike: 'represented',
    doubleStrike: 'represented',
    highlight: 'explicitly-omitted',
    shading: 'explicitly-omitted',
    verticalAlign: 'explicitly-omitted',
    baselineShiftPt: 'layout-only',
    caps: 'explicitly-omitted',
    smallCaps: 'explicitly-omitted',
    characterSpacingPt: 'layout-only',
    horizontalScalePercent: 'layout-only',
    kerningMinPt: 'layout-only',
    hidden: 'layout-only',
  } satisfies Record<keyof ResolvedRunStyle, MarkdownFieldPolicy>,
  link: {
    id: 'layout-only',
    kind: 'represented',
    href: 'represented',
    anchor: 'explicitly-omitted',
    tooltip: 'explicitly-omitted',
  } satisfies Record<keyof SpanLinkRecord, MarkdownFieldPolicy>,
  equation: {
    sourceNodeId: 'layout-only',
    geometry: 'explicitly-omitted',
    fallbackText: 'represented',
    truncated: 'explicitly-omitted',
  } satisfies Record<keyof EquationSpanRecord, MarkdownFieldPolicy>,
  line: {
    id: 'layout-only',
    range: 'represented',
    spans: 'represented',
    box: 'layout-only',
    contentX: 'layout-only',
    baseline: 'layout-only',
    leading: 'layout-only',
    trailingSpacing: 'layout-only',
    deletedRanges: 'layout-only',
    drawings: 'represented',
    anchorRevisions: 'explicitly-omitted',
  } satisfies Record<keyof LineRecord, MarkdownFieldPolicy>,
  paragraph: {
    kind: 'represented',
    id: 'layout-only',
    paragraphId: 'represented',
    fragmentIndex: 'represented',
    range: 'layout-only',
    props: 'explicitly-omitted',
    styleId: 'layout-only',
    outlineLevel: 'represented',
    alignment: 'represented',
    spacing: 'layout-only',
    indent: 'layout-only',
    bottomBorder: 'explicitly-omitted',
    borders: 'explicitly-omitted',
    shading: 'explicitly-omitted',
    shadingBox: 'layout-only',
    markRevisions: 'explicitly-omitted',
    markRevision: 'explicitly-omitted',
    markFormatRevision: 'explicitly-omitted',
    marker: 'represented',
    tabStops: 'layout-only',
    lines: 'represented',
    box: 'layout-only',
  } satisfies Record<keyof ParagraphFragmentRecord, MarkdownFieldPolicy>,
  listMarker: {
    text: 'explicitly-omitted',
    style: 'explicitly-omitted',
    box: 'layout-only',
    level: 'represented',
    numId: 'represented',
    numFmt: 'represented',
    ordinal: 'represented',
  } satisfies Record<keyof ListMarkerRecord, MarkdownFieldPolicy>,
  table: {
    kind: 'represented',
    id: 'layout-only',
    tableId: 'represented',
    fragmentIndex: 'layout-only',
    nestingDepth: 'layout-only',
    columnEdges: 'represented',
    rows: 'represented',
    box: 'layout-only',
  } satisfies Record<keyof TableFragmentRecord, MarkdownFieldPolicy>,
  tableRow: {
    id: 'represented',
    revisionKind: 'explicitly-omitted',
    revisionId: 'explicitly-omitted',
    revisionAuthor: 'explicitly-omitted',
    revisionDate: 'explicitly-omitted',
    rowIndex: 'layout-only',
    isHeaderRow: 'explicitly-omitted',
    isHeaderRepeat: 'represented',
    isContinuation: 'layout-only',
    cells: 'represented',
    box: 'layout-only',
  } satisfies Record<keyof TableRowFragmentRecord, MarkdownFieldPolicy>,
  tableCell: {
    id: 'layout-only',
    gridColumn: 'represented',
    gridColumnId: 'layout-only',
    gridSpan: 'represented',
    vMergeContinue: 'represented',
    paintInert: 'layout-only',
    rowSpan: 'explicitly-omitted',
    shading: 'explicitly-omitted',
    borders: 'explicitly-omitted',
    blocks: 'represented',
    box: 'layout-only',
  } satisfies Record<keyof TableCellFragmentRecord, MarkdownFieldPolicy>,
  inlineDrawing: {
    kind: 'callback-exposed',
    drawingNodeId: 'callback-exposed',
    paragraphId: 'represented',
    ownerPartName: 'callback-exposed',
    start: 'represented',
    x: 'callback-exposed',
    y: 'callback-exposed',
    width: 'callback-exposed',
    height: 'callback-exposed',
    distL: 'callback-exposed',
    distR: 'callback-exposed',
    distT: 'callback-exposed',
    distB: 'callback-exposed',
    advanceStart: 'represented',
    advanceEnd: 'callback-exposed',
    baselineOffset: 'callback-exposed',
    paintBounds: 'callback-exposed',
    hitBounds: 'callback-exposed',
    geometry: 'callback-exposed',
    resource: 'callback-exposed',
    accessibility: 'represented',
    hyperlinkHref: 'represented',
    effects: 'callback-exposed',
    crop: 'callback-exposed',
    transform: 'callback-exposed',
    placeholderGraphicKind: 'callback-exposed',
    vectorShape: 'callback-exposed',
    revisions: 'represented',
  } satisfies Record<keyof InlineDrawingRecord, MarkdownFieldPolicy>,
  anchoredDrawing: {
    kind: 'callback-exposed',
    drawingNodeId: 'callback-exposed',
    paragraphId: 'callback-exposed',
    ownerPartName: 'callback-exposed',
    start: 'callback-exposed',
    x: 'callback-exposed',
    y: 'callback-exposed',
    width: 'callback-exposed',
    height: 'callback-exposed',
    paintBounds: 'callback-exposed',
    hitBounds: 'callback-exposed',
    geometry: 'callback-exposed',
    resource: 'callback-exposed',
    accessibility: 'represented',
    hyperlinkHref: 'represented',
    effects: 'callback-exposed',
    crop: 'callback-exposed',
    transform: 'callback-exposed',
    placeholderGraphicKind: 'callback-exposed',
    vectorShape: 'callback-exposed',
    revisions: 'represented',
    anchorParagraphId: 'callback-exposed',
    horizontalFrame: 'callback-exposed',
    verticalFrame: 'callback-exposed',
    horizontalFrameOrigin: 'callback-exposed',
    verticalFrameOrigin: 'callback-exposed',
    behindDocument: 'callback-exposed',
    allowOverlap: 'callback-exposed',
    layoutInCell: 'callback-exposed',
    relativeHeight: 'callback-exposed',
    wrap: 'callback-exposed',
    layoutFallback: 'callback-exposed',
    sourceOrder: 'callback-exposed',
    textboxStory: 'explicitly-omitted',
  } satisfies Record<keyof AnchoredDrawingRecord, MarkdownFieldPolicy>,
  drawingAccessibility: {
    hidden: 'callback-exposed',
    decorative: 'callback-exposed',
    label: 'represented',
  } satisfies Record<keyof DrawingAccessibility, MarkdownFieldPolicy>,
  imageResourceKind: {
    ready: 'callback-exposed',
    unrenderable: 'callback-exposed',
    external: 'callback-exposed',
    missing: 'callback-exposed',
    pending: 'layout-only',
  } satisfies Record<ImageResourceState['kind'], MarkdownFieldPolicy>,
  textboxStory: {
    fragments: 'explicitly-omitted',
    flowHeight: 'explicitly-omitted',
    contentOffset: 'explicitly-omitted',
    contentWidth: 'explicitly-omitted',
    contentHeight: 'explicitly-omitted',
    fillHex: 'explicitly-omitted',
    strokeHex: 'explicitly-omitted',
    strokeWidthPt: 'explicitly-omitted',
    fallbackReason: 'explicitly-omitted',
    clippedResourceToken: 'layout-only',
  } satisfies Record<keyof TextboxStoryLayout, MarkdownFieldPolicy>,
  page: {
    id: 'layout-only',
    index: 'represented',
    box: 'layout-only',
    contentBox: 'layout-only',
    fragments: 'represented',
    columnSeparators: 'explicitly-omitted',
    anchoredDrawings: 'represented',
    header: 'represented',
    footer: 'represented',
    footnotes: 'represented',
    endnotes: 'represented',
    noteStream: 'layout-only',
    pageFieldSource: 'layout-only',
    hasBodyPageFields: 'layout-only',
    contentControls: 'explicitly-omitted',
  } satisfies Record<keyof PageRecord, MarkdownFieldPolicy>,
  headerFooter: {
    kind: 'layout-only',
    variant: 'layout-only',
    partName: 'layout-only',
    part: 'layout-only',
    rId: 'layout-only',
    box: 'layout-only',
    fragments: 'represented',
    anchoredDrawings: 'represented',
    pageFieldProjector: 'layout-only',
  } satisfies Record<keyof HeaderFooterStoryRecord, MarkdownFieldPolicy>,
  noteStory: {
    noteKind: 'layout-only',
    noteId: 'layout-only',
    scopeId: 'represented',
    mark: 'layout-only',
    continuation: 'layout-only',
    box: 'layout-only',
    fragments: 'represented',
  } satisfies Record<keyof NoteStoryRecord, MarkdownFieldPolicy>,
  noteSeparator: {
    kind: 'explicitly-omitted',
    box: 'layout-only',
    fragments: 'explicitly-omitted',
    synthetic: 'explicitly-omitted',
    ruleStyle: 'explicitly-omitted',
  } satisfies Record<keyof NonNullable<NoteAreaRecord['separator']>, MarkdownFieldPolicy>,
  noteArea: {
    kind: 'layout-only',
    placement: 'layout-only',
    box: 'layout-only',
    separator: 'explicitly-omitted',
    notes: 'represented',
    fallbackReason: 'explicitly-omitted',
  } satisfies Record<keyof NoteAreaRecord, MarkdownFieldPolicy>,
  layout: {
    revision: 'layout-only',
    displayMode: 'represented',
    pages: 'represented',
    contentControls: 'explicitly-omitted',
    controlContextToken: 'layout-only',
  } satisfies Record<keyof SemanticLayout, MarkdownFieldPolicy>,
  paragraphAlignment: {
    left: 'represented',
    center: 'represented',
    right: 'represented',
    both: 'represented',
  } satisfies Record<ParagraphFragmentRecord['alignment'], MarkdownFieldPolicy>,
  revisionKind: {
    insert: 'explicitly-omitted',
    delete: 'represented',
    moveFrom: 'represented',
    moveTo: 'explicitly-omitted',
    format: 'explicitly-omitted',
  } satisfies Record<RevisionKind, MarkdownFieldPolicy>,
  revisionAttribution: {
    kind: 'represented',
    id: 'explicitly-omitted',
    author: 'explicitly-omitted',
    date: 'explicitly-omitted',
    nodeId: 'explicitly-omitted',
  } satisfies Record<keyof RevisionAttribution, MarkdownFieldPolicy>,
  revisionDisplayMode: {
    'all-markup': 'represented',
    proposed: 'represented',
    original: 'represented',
  } satisfies Record<RevisionDisplayMode, MarkdownFieldPolicy>,
  noteNavigationDirection: {
    'to-note': 'represented',
    'to-body': 'represented',
  } satisfies Record<NonNullable<StyleSpanRecord['noteNav']>['direction'], MarkdownFieldPolicy>,
  linkKind: {
    external: 'represented',
    internal: 'explicitly-omitted',
    unresolved: 'explicitly-omitted',
  } satisfies Record<SpanLinkRecord['kind'], MarkdownFieldPolicy>,
  rootStoryKind: {
    body: 'represented',
    header: 'represented',
    footer: 'represented',
    footnote: 'represented',
    endnote: 'represented',
    'note-separator': 'explicitly-omitted',
  } satisfies Record<SemanticRootStoryKind, MarkdownFieldPolicy>,
});

void MARKDOWN_SEMANTIC_POLICY_RATCHETS;
